### ISSUE TITLE
global logger

### ISSUE THREAD

**Issue by cclauss** [marcus67/gitsynchista#11]
A question more than an issue...  I have not done much logging in the past.

Many functions and methods start with `global logger`.  My understanding was that the `global` keyword is only _required_ when you are going to reset the value of a variable.  Is `global` really needed in all of these functions and methods or are you merely using it to signal to the reader that `logger` is defined elsewhere?

**Comment by marcus67** [comment]
Well, it does definitely not have to do anything with logging. It's a general approach. I've had some nasty (read: hard to find) bugs when I do not use the `global` keyword strictly. It is easier to me to always use it than trying to find out whether it's really neccessary in a specific context. As far as the naming is concerned it would probably even better to also use a prefix such as `global g_logger`.

**Comment by cclauss** [comment]
Makes sense.
